In [66]:
import tifffile
import numpy as np
import time
import pandas as pd

import matplotlib.pyplot as plt
from skimage.feature import peak_local_max
from skimage import img_as_float

import os
import h5py
from tqdm import tqdm

In [83]:
in_dir = r'..\images\HCH\registered'
cells_to_process = 'hch'
experiment = 'exp1'
rel_thre_dict = {'cycle1': {'bm': [1.0, 0.04, 0.1], 'uc': [1.0, 0.02, 0.1]},
                 'cycle2': {'bm': [0.04, 0.06, 0.02], 'uc': [0.03, 0.035, 0.1]},
                 'cycle3': {'bm': [0.12, 0.027, 0.08], 'uc': [0.2, 0.025, 0.07]},
                 'cycle4': {'bm': [0.03, 0.06, 0.08], 'uc': [0.02, 0.03, 0.02]},
                 'cycle5': {'bm': [0.02, 0.06, 0.08], 'uc': [0.02, 0.03, 0.02]},
                 'cycle6': {'bm': [0.02, 0.06, 0.13], 'uc': [0.03, 0.03, 0.02]},
                 'cycle7': {'bm': [0.04, 0.03, 0.04], 'uc': [0.025, 0.025, 0.02]},
                 'cycle8': {'bm': [0.025, 0.032, 0.04], 'uc': [0.03, 0.035, 0.02]},
                 'cycle9': {'bm': []}
                }

abs_thre_dict = {'cycle1': {'bm': [3200, 20000, 4500], 'uc': [1400, 5800, 1700]},
                 'cycle2': {'bm': [4200, 6500, 7500], 'uc': [3200, 2750, 4200]},
                 'cycle3': {'bm': [2500, 20000, 2000], 'uc': [20000, 1300, 2450]},
                 'cycle4': {'bm': [5000, 4500, 5100], 'uc': [20000, 3800, 2650]},
                 'cycle5': {'bm': [20000, 3600, 4800], 'uc': [20000, 5150, 1500]}
                }
"""
abs_thre_dict = {'cycle1': {'bm': [2600, 20000, 3300], 'uc': [2600, 40000, 5100]},
                 'cycle2': {'bm': [4200, 5200, 7500], 'uc': [2800, 4000, 1300]},
                 'cycle3': {'bm': [3400, 20000, 2000], 'uc': [1500, 40000, 1200]},
                 'cycle4': {'bm': [5000, 5100, 5100], 'uc': [4200, 4200, 3800]},
                 'cycle5': {'bm': [20000, 4000, 5100], 'uc': [40000, 5200, 3600]}
                }
"""
hch_abs_thre_dict = {'cycle1': {'hch': [40000, 3900, 3000]},
                     'cycle2': {'hch': [2500, 6500, 1000]},
                     'cycle3': {'hch': [1000, 2000, 1200]},
                     'cycle4': {'hch': [1300, 4500, 3200]},
                     'cycle5': {'hch': [2600, 3200, 3200]},
                     'cycle6': {'hch': [40000, 3200, 1300]}
                    }

In [84]:
fn_l = os.listdir(in_dir)
fn_l.sort()
# fn_l = fn_l[:26]

In [85]:
markers_l = []
l = os.listdir(os.path.join(in_dir, fn_l[0]))
for n in l:
    if n.startswith('cycle'):
        n = n[:len(n)-4]
        markers_l = markers_l + n.split('_')[1:4]
for i in range(len(markers_l)):
    markers_l[i] = markers_l[i].upper()
print(markers_l)

['EMPTY', 'EEF2', 'ACTB', 'SOX9', 'GAPDH', 'SPP1', 'IL8', 'IL6', 'CCL11', 'COL5A2', 'COL1A1', 'PDL1', 'MALAT1', 'RUNX1', 'CXCR4', 'EMPTY', 'MKI67', 'NANOG', 'CONA', 'PHA', 'WGA']

In [86]:
def save_hdf5(path:str, name:str, data: np.ndarray, attr_dict= None, mode:str='a') -> None:
    # Read h5 file
    hf = h5py.File(path, mode)
    # Create z_stack_dataset
    if hf.get(name) is None:
        data_shape = data.shape
        data_type = data.dtype
        chunk_shape = (1, ) + data_shape[1:]
        max_shape = (data_shape[0], ) + data_shape[1:]
        dset = hf.create_dataset(name, shape=data_shape, maxshape=max_shape, chunks=chunk_shape, dtype=data_type, compression="gzip")
        dset[:] = data
        if attr_dict is not None:
            for attr_key, attr_val in attr_dict.items():
                dset.attrs[attr_key] = attr_val
    else:
        print(f'Dataset {name} exists')
        
    hf.close()

def dot_detect_thre_rel(im, threshold_rel):
    im = img_as_float(im)
    coordinates = peak_local_max(im, threshold_rel=threshold_rel)
    peak_mask = np.zeros_like(im, dtype=bool)
    peak_mask[tuple(coordinates.T)] = True
    return peak_mask

def dot_detect_thre_abs(im, threshold_abs):
    coordinates = peak_local_max(im, threshold_abs=threshold_abs)
    peak_mask = np.zeros_like(im, dtype=bool)
    peak_mask[tuple(coordinates.T)] = True
    return peak_mask

def count_dots(cells, roi, masks, rna_masks, exps):
    cell_id = []
    count = []
    for i in range(len(masks)):
        mask = masks[i].reshape(masks[i].shape[0], masks[i].shape[1], 1)
        count.append(np.sum(np.sum(mask*rna_masks,axis=0),axis=0))
        cell_id.append(exps+'_'+cells+'_'+roi+"_"+str(i+1))
    return cell_id, count

In [88]:
# Detect by absolute threshold
expression = []
cell_ids = []
for fn in tqdm(fn_l):
    l = os.listdir(os.path.join(in_dir, fn))
    l.sort()
    masks = []
    genes = []
    rna_masks = []
    for n in l:
        if n.endswith('.tif'):
            if n.startswith('cycle'):
                if n.startswith('cycle7'):
                    continue
                temp = n[:len(n)-4].split('_')
                thre = hch_abs_thre_dict[temp[0]][cells_to_process]
                im = tifffile.imread(os.path.join(in_dir, fn, n))
                if im.ndim == 4:
                    im = im.reshape(im.shape[1], im.shape[2], im.shape[3])

                genes.append(im[:,:,1])
                rna_masks.append(dot_detect_thre_abs(im[:,:,1], threshold_abs=thre[0]))

                genes.append(im[:,:,2])
                rna_masks.append(dot_detect_thre_abs(im[:,:,2], threshold_abs=thre[1]))

                genes.append(im[:,:,3])
                rna_masks.append(dot_detect_thre_abs(im[:,:,3], threshold_abs=thre[2]))
            else:
                mask = (tifffile.imread(os.path.join(in_dir, fn, n))>0).astype('int')
                if len(mask.shape) == 3:
                    mask = mask.reshape(mask.shape[1], mask.shape[2])
                masks.append(mask)
    roi_cell_id, roi_count = count_dots(cells_to_process, fn, masks, np.dstack(rna_masks), experiment)
    save_hdf5(path=os.path.join(in_dir, fn, 'gene_count_abs_threshold_'+fn+'.hdf5'), name='gene_count_abs_threshold_'+fn, data=np.dstack(rna_masks))
    cell_ids = cell_ids + roi_cell_id
    expression = expression + roi_count

 91%|██████████████████████████████████████████████████████████████████████████▍       | 59/65 [18:21<01:52, 18.67s/it]

ValueError: need at least one array to concatenate

In [89]:
len(expression)

256

In [90]:
len(cell_ids)

256

In [91]:
expression_array = np.vstack(expression)

In [95]:
df = pd.DataFrame(expression_array, columns=markers_l[:18], index=cell_ids)

In [97]:
df = df.drop(columns='EMPTY')

In [96]:
df

,EMPTY,EEF2,ACTB,SOX9,GAPDH,SPP1,IL8,IL6,CCL11,COL5A2,COL1A1,PDL1,MALAT1,RUNX1,CXCR4,EMPTY,MKI67,NANOG
exp1_hch_001_1,0,1065,1515,35931,14,3460,36,431,14,809,1215,7,698,117,57,0,98,21
exp1_hch_001_2,0,406,1054,16634,1,1602,7,277,2,161,397,2,398,43,20,0,9,6
exp1_hch_001_3,0,964,785,11532,9,1840,8,333,3,297,688,2,349,26,20,0,14,16
exp1_hch_001_4,0,668,714,16556,13,1313,19,132,5,300,860,2,452,48,19,0,14,9
exp1_hch_001_5,0,836,799,16842,3,1581,8,177,4,314,918,6,427,60,31,0,9,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
exp1_hch_034_6,0,694,1099,6,454,4,9,168,6,165,619,5,228,6,36,0,11,2
exp1_hch_034_7,0,629,1084,6,476,4,2,165,5,81,495,4,135,2,11,0,5,6
exp1_hch_034_8,0,1003,1447,3,824,8,5,317,9,256,669,3,370,8,22,0,25,5
exp1_hch_034_9,0,926,1156,9,864,4,7,354,5,124,633,8,308,8,17,0,22,2
exp1_hch_034_10,0,293,690,3,332,6,5,114,1,226,7,2,144,6,13,0,89,1

In [98]:
out_dir = r'..\images\HCH\registered'
df.to_csv(os.path.join(out_dir, r'hch_abs_thre_expression_16_genes.csv'))